# For small Robots
INTENT_INPUT = "INTENT_INPUT"
INTENT_PARSE = "INTENT_PARSE"
INTENT_DECIDE = "INTENT_DECIDE"
INTENT_ACTION = "INTENT_ACTION"
INTENT_FEEDBACK = "INTENT_FEEDBACK"

# API 专用意图
INTENT_PARSE_URL = "INTENT_PARSE_URL"
INTENT_HTTP_REQUEST = "INTENT_HTTP_REQUEST"
INTENT_HANDLE_SUCCESS = "INTENT_HANDLE_SUCCESS"
INTENT_HANDLE_ERROR = "INTENT_HANDLE_ERROR"
INTENT_EXTRACT_DATA = "INTENT_EXTRACT_DATA"
INTENT_OUTPUT_SUCCESS = "INTENT_OUTPUT_SUCCESS"
INTENT_OUTPUT_ERROR = "INTENT_OUTPUT_ERROR"